### ISSUE TITLE
NameError: name 'SocketIO' is not defined @ step 4 of tutorial

### ISSUE THREAD

**Issue by aspiringguru** [tutorialstechnology/flask_websockets#2]
I'm sure this is a simple problem, kindof surprised I couldn't sort this out. 

error message below indicates error is in websockets.py @ this line
@socketio.on('client_connected')

I encountered this error at step 4 of the tutorial, just after creating websockets.py.
https://tutorials.technology/tutorials/61-Create-an-application-with-websockets-and-flask.html

thought it might be a naming error since socketio 'not defined' might have been due to 
socketio != SocketIO & socketio != socket.io etc.

from flask_socketio import SocketIO

my git repo @ point of error.
https://github.com/aspiringguru/flaskWebsocketsIO/tree/83007df9ec8cbf008d30f996e5cc89d99513fd90

 ./run.sh
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\username\Anaconda3\Scripts\flask-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\username\Anaconda3\lib\site-packages\flask\cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\username\Anaconda3\lib\site-packages\flask\cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "C:\Users\username\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\username\Anaconda3\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Users\username\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\username\Anaconda3\lib\site-packages\flask_socketio\cli.py", line 72, in run
    run_server()
  File "C:\Users\username\Anaconda3\lib\site-packages\flask_socketio\cli.py", line 57, in run_server
    app = info.load_app()
  File "C:\Users\username\Anaconda3\lib\site-packages\flask\cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "C:\Users\username\Anaconda3\lib\site-packages\flask\cli.py", line 90, in locate_app
    __import__(module)
  File "C:\2018_working\git_repos\FBchatbot\flask_websockets\app.py", line 5, in <module>
    from websockets import (
  File "C:\2018_working\git_repos\FBchatbot\flask_websockets\websockets.py", line 4, in <module>
    @SocketIO.on('client_connected')
NameError: name 'SocketIO' is not defined
 * Serving Flask-SocketIO app "app"
 * Forcing debug mode on

**Comment by facorazza** [comment]
`pip3 install flask-socketio`?
